### ISSUE TITLE
TypeError in model.forward()

### ISSUE THREAD

**Issue by SummerRainQ** [dino-chiio/blip-vqa-finetune#8]
I use your code but add lora to model, because I dont have enough CUDA memory
```
model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")

# add lora
lora_config = AdaLoraConfig(
    task_type=TaskType.QUESTION_ANS,
    r=8,
    init_r=12,
    tinit=200,
    tfinal=1000,
    deltaT=10,
    lora_alpha=32,
    target_modules=["query", "value"],
    lora_dropout=0.1
)
model = get_peft_model(model, lora_config)
```
After I do this and run the finetune.py, I got TypeError

> Traceback (most recent call last):
  File "/workspaces/huggingface/finetune_blip.py", line 97, in <module>
    outputs = model(input_ids=input_ids,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 2312, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/adalora/model.py", line 237, in forward
    outputs = self.model.forward(*args, **kwargs)
TypeError: BlipForQuestionAnswering.forward() got an unexpected keyword argument 'inputs_embeds'

**Comment by dino-chiio** [comment]
I think you should check the version of transformers. During maintenance, some functions may be changed.

**Comment by SummerRainQ** [comment]
I changed the transformers package to your setting version 4.35.2 and still encountered the same problem.

**Comment by SummerRainQ** [comment]
I found that the problem lies in lora config. If task_type=TaskType.QUESTION_ANS is set in lora config, peft model will let the model return inputs_embeds, but there is no such parameter in the forward of BLIP model, so TypeError: BlipForQuestionAnswering.forward() will got an unexpected keyword argument 'inputs_embeds'
The solution is to turn off the task_type setting
